name: 🧪 Development

on:
  push:
    branches:
      - chore/**
      - feature/**
      - fix/**

    paths:
      - '.github/workflows/development.yml'
      - 'src/**'
      - 'husky-hooks.config.default.js'
      - 'package.json'
      - 'tsconfig.json'
      - 'package-lock.json'

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      node_versions: '[22, 24]'
