name: 🚀 Main

on:
  push:
    branches:
      - main

    paths:
      - '.github/workflows/main.yml'
      - 'src/**'
      - 'husky-hooks.config.default.js'
      - 'package.json'
      - 'tsconfig.json'
      - 'package-lock.json'

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      node_versions: '[24]'
