name: "📦 publish"

on:
  push:
    tags:
      - "*"

env:
  NODE_ENV: "development"
  RUNTIME_ENV: "main"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install depencencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish package
        uses: JS-DevTools/npm-publish@v4
        with:
          token: ${{ secrets.NPM_TOKEN }}
