name: 🤖 Renovate

on:
  push:
    branches:
      - renovate/**

    paths:
      - '.github/workflows/renovate.yml'
      - 'package.json'
      - 'package-lock.json'

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      node_versions: '[20, 22]'
